---
title: "Combine Responses"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # Set WD to Root
library(tidyverse)

```

combine_resp
combine_resp.list
combine_resp.data.frame

# Combine Response Generic

```{r combine_resp}
combine_resp <- function(data,
                         # Clean
                         id_regex = ".*", # Extract ID from Email
                         sep_name = " ", # Separate First name and Surname
                         # Encode
                         state = c("Finished", "In progress"),
                         encode = c(1,0),
                         choose_encode = c("max", "min", "all"),
                         choose_time = c("first", "last", "all"),
                         # Split cloze
                         split_cloze = F, 
                         part_glue = "_part_",
                         ... # passed to sep_col arg
                         ) {
  
  UseMethod("combine_resp")
}

tech_resp_df1_raw %>% combine_resp(sep_name = "-", split_cloze = F)
tech_resp_ls_raw %>% combine_resp(sep_col = ":")
```


# Combine Response for list 

Extra arg = sep_col



```{r combine_resp.list}
combine_resp.list <- function(data,
                              # Clean
                              id_regex = ".*", # Extract ID from Email
                              sep_name = " ", # Separate First name and Surname
                              sep_col = "_", # Separation for State and Response column names
                              # Encode
                              state = c("Finished", "In progress"),
                              encode = c(1,0),
                              choose_encode = c("max", "min", "all"),
                              choose_time = c("first", "last", "all"),
                              # Split cloze
                              split_cloze = F, 
                              part_glue = "_part_"
                              ) {
  
  if(!is_named_list_data.frame(data)) stop("`data` must be named list of data.frame", call. = F)
  is_data_resp_rep <- purrr::every(data, is_responses_report)
  if(!is_data_resp_rep) stop("Elements of `data` must be Moodle Responses report",call. = F)
  data %>% 
    purrr::map(~combine_resp.data.frame(.x,
                                    # Clean
                                    id_regex = id_regex, # Extract ID from Email
                                    sep_name = sep_name, # Separate First name and Surname
                                    # Encode
                                    state = state,
                                    encode = encode,
                                    choose_encode = choose_encode, 
                                    choose_time = choose_time,
                                    # Split cloze
                                    split_cloze = split_cloze, 
                                    part_glue = part_glue
                                    )) %>% 
    purrr::map(~dplyr::select(.x, Name, ID, State, starts_with("R"))) %>% 
    # Prefix column "Responses" and "State" with names(list)
    rename_with_ls_df_names(.cols = starts_with("R"), sep = sep_col) %>% 
    rename_with_ls_df_names(.cols = starts_with("S"), sep = sep_col) %>% 
   
    purrr::reduce(dplyr::full_join, by = c("ID", "Name"))
  
}

tech_resp_ls_raw %>% 
  combine_resp.list(split_cloze = F, sep_col = "_") 
```

```{r}
tech_grad_ls_raw %>% combine_resp.list()
tech_resp_df1_raw %>% combine_resp.list()
```

```{r}
tech_resp_ls_raw %>% 
  map(~combine_resp.data.frame(.x, split_cloze = F)) %>% 
  
  map(~dplyr::select(.x, Name, ID, State, starts_with("R"))) %>% 
  rename_with_ls_df_names(.cols = starts_with("R")) %>% 
  rename_with_ls_df_names(.cols = starts_with("S")) %>% 
  
  purrr::reduce(full_join, by = c("ID", "Name")) %>% names()
```
```{r}
tech_grad_df2_raw %>% 
  rename_with(.cols = contains("name"), ~paste0("Prefix_", .x))
```


# Combine Response for DF



```{r combine_resp.data.frame}
combine_resp.data.frame <- function(data,
                                    # Clean
                                    id_regex = ".*", # Extract ID from Email
                                    sep_name = " ", # Separate First name and Surname
                                    # Encode
                                    state = c("Finished", "In progress"),
                                    encode = c(1,0),
                                    choose_encode = c("max", "min", "all"),
                                    choose_time = c("first", "last", "all"),
                                    # Split cloze
                                    split_cloze = F, 
                                    part_glue = "_part_"
                                    ) {
  
  if(!is_responses_report(data)) stop("`data` is not a Moodle Responses report.", call. = F)
  
  data_enc <- data %>% 
    clean_moodle(id_regex = id_regex, sep_name = sep_name, 
                 force_numeric = FALSE, dash_na = FALSE) %>% 
    encode_moodle(state = state, encode = encode, 
                  choose_encode = choose_encode, 
                  choose_time = choose_time)
  
  # If not split cloze column; return
  if(!split_cloze) return(data_enc) 
  # If choose to split_cloze and not found cloze col; Error
  if(!has_cloze_col(data_enc)) stop("This Moodle Responses report has no Cloze column to split")
  
  cloze_col_nm <- get_cloze_col_names(data_enc)
  split_cloze(data_enc, part_glue = part_glue)

}

tech_resp_df2_raw %>% 
  combine_resp.data.frame(split_cloze = T) 
```

```{r}
tech_resp_ls_raw[[2]] %>% clean_moodle() %>% encode_moodle2()
```


```{r}
tech_grad_df2_raw %>% combine_resp.data.frame(split_cloze = T) 
```
```{r}
tech_resp_ls_raw %>% map(has_cloze_col)
```





```{r}
match(c(1,2), c(1,3,2,4))

c(1,3,2,4)[-c(1,3)]
```

```{r}

c("Petal.Length", "Species") %>% 
 map(~select(iris, .x))
```

### How to sort vector by names

```{r}
lst2 <- setNames(list(5,4,7,9,2), c(1,3,4,2,5))

lst2

lst2[order(names(lst2))]
```





```{r}
split_cloze_col(select(tech_resp_df2_raw, "Response 1"), "Response 1" )
```


```{r}
tech_resp_df2_raw %>% 
  clean_moodle() %>% 
  encode_moodle() %>% 
  
  split_cloze_col(Response_1)
```


