---
title: "Data & Namespace Usage"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # Set WD to Root
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
here::i_am("develop/data.Rmd")
```

# Namespace usage

```{r}
require(tidyselect)
require(rlang)
require(dplyr)
require(purrr)
require(tidyr)
require(stringr)
require(lubridate) # lubridate::dmy_hm
```


```{r}
names(tech_grad_df2_raw)
names(tech_resp_df1_raw)

tech_resp_df1_raw
```


# Read Responses


## Techno

```{r}
tech_resp_ls_raw <- lbr::rd(read_csv, path = "data/Responses", pattern = "Techno")

tech_resp_df1_raw <- tech_resp_ls_raw$Techno_1_resp_essay
tech_resp_df2_raw <- tech_resp_ls_raw$`Techno_2_resp_no-essay`
```

## 319: RS case 4

```{r}
rs4_resp_ls <- lbr::rd(read_csv, path = "data/Responses", pattern = "RS4")
```

## Responses with Question stem

319: RS case 2

```{r}
rs2_respmix_ls <- lbr::rd(read_csv, path = "data/Responses", pattern = "RS2")
```

```{r}
rs2_respmix_ls[[1]] %>% names()
```


```{r}
tech_resp_df1_raw 

rs4_resp_ls
```

```{r}
tech_resp_df2_raw
```

## PO NCV

```{r ncv_po_resp_raw}
ncv_po_resp_raw <- read_csv(here("data/Responses/NCV_PO_resp.csv"))

ncv_po_resp_raw
```


### Some Has no "Grade" column ??

```{r}
int_nerv_resp <- read_csv("data/Responses/Int_nervous_resp.csv")

int_nerv_resp %>% names()
```

## Multiple Answered MCQ

```{r}
repro_mans_resp_ls <- list(
csv = read_csv("data/Responses/SIID223-63-Summative-Part 2_responses.csv"),
excel = readxl::read_excel("data/Responses/SIID223-63-Summative-Part 2_responses.xlsx")
)

repro_mans_resp_ls
```



# Read Grades

## Techno Only Numeric Grade

```{r}
tech_grad_ls_raw <- lbr::rd(read_csv, path = "data/Grades", pattern = "_num")

tech_grad_df2_raw <- tech_grad_ls_raw$Techno_2_grade_num
```

## Non-numeric Grades file

```{r}
tech_nograd_df1 <- read_csv("data/Grades/Techno_1_grade_notyet.csv")
```



## Multiple Attempt Grades

```{r}
tm_mgrad_raw <- read_csv("./data/Grades/TM_grade_num_multi.csv")

f2_mgrad_raw <- read_csv("data/Grades/SIID222_Formative_2_num_multi.csv")

tm_mgrad_raw 
f2_mgrad_raw
```

## Varient: ID in Institution col

```{r tm_ncv_gr}
tm_ncv_gr <- read_csv("data/Grades/TM-NCV-Student-ID_Varient_Gr.csv")

tm_ncv_resp <- read_csv("data/Responses/TM-NCV-Student-ID_Varient_Resp.csv")
```


# ID

```{r}
tech_id <- read_csv("data/ID/techno_id.csv") %>% map_df(as.character)

tech_id
```


