---
title: "Logical Validation"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # Set WD to Root
library(tidyverse)
library(testthat)
```

[source](https://docs.moodle.org/310/en/Quiz_reports)

# Grade vs Responses Report

#### Regex for check Grade vs Responses Report

```{r report_col_regex}
report_col_regex <- list(
  moodle = c("Surname", "First name", "Email address", "State"),
  grades = c("Surname", "First name", "Email address", "State", "Grade", "Q\\."),
  responses = c("Surname", "First name", "Email address", "State", "Response")
)
```

## Moodle Quiz Type

```{r get_report_type}
get_report_type <- function(data) {
  
  if(!is.data.frame(data)) stop("`data` must be a data.frame", call. = F)
  is_gr <- is_grades_report(data)
  is_resp <- is_responses_report(data)
  out <- if(is_gr){ 
    "Grades"
  }else if(is_resp){
    "Responses"
  }else{
     NA_character_
  }
  out
}

get_report_type(tech_grad_df2_raw)
get_report_type(tech_resp_df1_raw)
get_report_type(iris)
```

```{r}
test_that("get_report_type output test",{
  
  # Output
  get_report_type(tech_grad_df2_raw) %>% expect_equal("Grades")
  get_report_type(tech_resp_df1_raw) %>% expect_equal("Responses")
  get_report_type(iris) %>% expect_equal(NA_character_)
  # Error Msg
  get_report_type(list(iris)) %>% expect_error()
  
})
```


## Is it Moodle Report

```{r is_report}
is_report <- function(data) {
  
  if(!is.data.frame(data)) stop("`data` must be a data.frame", call. = F)
  all(is_regex_in_names(data, report_col_regex$moodle))
}

is_report(tech_grad_df2_raw)
is_report(tech_resp_df1_raw)
is_report(iris)

is_report(ncv_po_resp_raw)
```



```{r}
int_nerv_resp %>% 
  is_regex_in_names(report_col_regex$moodle, verbose = T)
```


```{r}
test_that("is_report",{
  
  is_report(tech_grad_df2_raw) %>% expect_true()
  is_report(tech_resp_df1_raw) %>% expect_true()
  is_report(iris) %>% expect_false()
  # Error
  is_report(1:10) %>% expect_error()
  
})
```


## Is it Grades Report

```{r is_grades_report}
is_grades_report <- function(data) {
  
  if(!is.data.frame(data)) stop("`data` must be a data.frame", call. = F)
  all(is_regex_in_names(data, report_col_regex$grades))
  
}

is_grades_report(tech_grad_df2_raw)
is_grades_report(tech_resp_df1_raw)

is_grades_report(ncv_po_resp_raw)
```

```{r}
tech_grad_df2_raw %>% 
  names() %>% 
  str_subset("Q\\.")
```


```{r}
test_that("is_grades_report",{
  
  is_grades_report(tech_grad_df2_raw) %>% expect_true()
  is_grades_report(tech_resp_df1_raw) %>% expect_false()
  is_grades_report(iris) %>% expect_false()

  is_grades_report(1:10) %>% expect_error()
  
})
```

## Is it Responses Report

```{r is_responses_report}
is_responses_report <- function(data) {
  
  if(!is.data.frame(data)) stop("`data` must be a data.frame", call. = F)
  all(is_regex_in_names(data, report_col_regex$responses))
  
}

is_responses_report(tech_resp_df1_raw)
is_responses_report(tech_grad_df2_raw)
is_responses_report(tech_grad_ls_raw)

is_responses_report(ncv_po_resp_raw)
```

```{r}
test_that("is_responses_report",{
  
  is_responses_report(tech_grad_df2_raw) %>% expect_false()
  is_responses_report(tech_resp_df1_raw) %>% expect_true()
  is_responses_report(iris) %>% expect_false()

  is_responses_report(1:10) %>% expect_error()
  
})
```


# Check Regex in names of object

check if all elecment of regular expression are presented in names of the object

```{r is_regex_in_names }
valid_regex <- c("First name", "Surname")
valid_regex2 <- c("First name", "Surname", "z", "y")


is_regex_in_names <- function(x, regex, verbose = F){
  
  nm <- names(x)
  lgl_ls <- purrr::map(nm, ~stringr::str_detect(.x, regex))
  lgl_ls_t <- purrr::map(purrr::transpose(lgl_ls), ~unlist(.x, recursive = F))
  lgl_vctr <- purrr::map_lgl(lgl_ls_t, any)
  
  if(verbose && !all(lgl_vctr)){
    no_match <- regex[which(!lgl_vctr)]
    message("The following not presented in `x`")
    print_msg(no_match, sep = ", ")
  }
  
  lgl_vctr

}

is_regex_in_names(tech_grad_df2_raw, valid_regex2, verbose = T)
```


### Helper fn: `print_msg`

```{r print_msg }
print_msg <- function(x, ... , sep = "\n", domain = NULL, appendLF = TRUE){
  
  x_comb <- purrr::reduce(x, paste, sep = sep)
  message(x_comb, ..., domain = domain, appendLF = appendLF)
  
}

print_msg(valid_regex2)
```

```{r}
valid_regex %>% reduce(paste, sep = " vs ")
```

```{r}
names(tech_grad_df2_raw) %>% 
  map( ~str_detect(.x, valid_regex2)) %>% 
  transpose() %>% map(~unlist(.x, recursive = F)) %>%  

  map_lgl(any) 
```

# Has Grade column ?


No Grade column

```{r}
int_nerv_resp %>% is_regex_in_names("Grade")
```

Has Grade column

```{r}
tech_resp_df1_raw %>% is_regex_in_names("Grade")
```


# Numeric Grade or "Not yet graded"

```{r is_some_grade_numeric}
is_some_grade_numeric <- function(data){
  
  require(dplyr)
  data %>% 
    dplyr::select(tidyselect::starts_with("Grade")) %>% 
    unique() %>% 
    dplyr::pull() %>% 
    # Detect start with one or more digit can be followed by dot and end with digit
    stringr::str_detect("^[:digit:]+\\.?[:digit:]+$") %>% 
    any()
  
}

tech_resp_df1_raw %>% is_some_grade_numeric()
tech_resp_df2_raw %>% is_some_grade_numeric()
```


```{r is_some_grade_nyg}
is_some_grade_nyg <- function(data){
  
  require(dplyr)
  data %>% 
    dplyr::select(tidyselect::starts_with("Grade")) %>% 
    unique() %>% 
    dplyr::pull() %>% 
    # Detect any "Not yet graded"
    stringr::str_detect("Not yet graded") %>% 
    any()
  
}

tech_resp_df1_raw %>% is_some_grade_nyg()

tech_nograd_df1 %>% is_some_grade_nyg()
tech_nograd_df1 %>% is_some_grade_numeric()
```


```{r}
tech_resp_df1_raw %>% 
  filter(`Grade/10.00` == "-")
```

```{r}
tech_resp_df1_raw %>% 
  select(starts_with("Grade")) %>% 
  unique() %>% 
  pull() %>% 
  str_detect("Not yet graded")
```



```{r}
tech_resp_df1_raw %>% 
  select(starts_with("Grade")) %>% 
  unique() %>% 
  pull() %>% 
  str_detect("^[:digit:]+\\.?[:digit:]+$")
```

```{r}
c(12.3, "a123", "122.2", "12.23.3" ,"12a", NA, "") %>% 
 str_extract("^[:digit:]+\\.?[:digit:]+$")
```

```{r}
c("abc", "DEF") %>% str_detect("(abc)|(DEF)")
```



